online_bookstore/apps/book/urls.py
# book/urls.py
from django.contrib.auth.views import PasswordChangeDoneView
from django.urls import path
from .views import (
    RegisterView, HomePageView, BookDetailView, CataloguePageView,
    EditBookView, PublishBookView, DeleteBookView, ProfilePageView,
    LoginUserView, LogoutUserView, MyOrdersView, EditReviewView,
    AboutUsView, CustomPasswordChangeView, UserListView, UserOrdersUpdateView, DeleteOrderView
)

urlpatterns = [
    path('', HomePageView.as_view(), name='home-page'),

    path('login/', LoginUserView.as_view(), name='login'),
    path('logout/', LogoutUserView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),

    path('profile/', ProfilePageView.as_view(), name='profile-page'),
    path('password-change/', CustomPasswordChangeView.as_view(), name='password-change'),
    path('password-change/done/',
         PasswordChangeDoneView.as_view(template_name='registration/password-change-done.html'),
         name='password-change-done'),

    path('profile/my-orders/', MyOrdersView.as_view(), name='my-orders'),

    path('about-us/', AboutUsView.as_view(), name='about-us'),
    path('catalogue/', CataloguePageView.as_view(), name='catalogue-page'),
    path('book-detail/<int:pk>/', BookDetailView.as_view(), name='book-detail'),
    path('edit-review/<int:review_id>/', EditReviewView.as_view(), name='edit-review'),

    # For Staff only
    path('publish/', PublishBookView.as_view(), name='publish-book'),
    path('delete-book/<int:pk>/', DeleteBookView.as_view(), name='delete-book'),
    path('edit-book/<int:pk>/', EditBookView.as_view(), name='edit-book'),
    path('users/', UserListView.as_view(), name='user-list'),
    path('users/<str:username>/orders/', UserOrdersUpdateView.as_view(), name='user-orders-update'),
    path('order/delete/<int:pk>/', DeleteOrderView.as_view(), name='order-delete'),
]

online_bookstore/urls.py
# project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.core.mail import send_mail
from django.urls import path, include
from online_bookstore.apps.book.views import Custom404View

handler404 = Custom404View.as_view()

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('online_bookstore.apps.book.urls')),
    path('', include('online_bookstore.apps.store.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# send_mail(
#     subject='Registration successful',
#     message='Hello',
#     from_email='greetings@emporium.com',
#     recipient_list=('nikolaycholakovdemo@gmail.com', )
# )

online_bookstore/apps/book/models.py
# book/models.py

from django.contrib.auth.models import User, AbstractUser
from django.core import validators
from django.db import models


class Customer(AbstractUser):
    NAME_MAX_LEN = 30
    NAME_MIN_LEN = 2

    EMAIL_MAX_LEN = 50
    DELIVERY_ADDRESS_MIN_LEN = 10
    DELIVERY_ADDRESS_MAX_LEN = 250

    MIN_AGE_VALUE = 1
    MAX_AGE_VALUE = 150

    email = models.EmailField(
        max_length=EMAIL_MAX_LEN,
        unique=True,
        null=True,
        validators=[
            validators.EmailValidator()
        ]
    )
    age = models.PositiveIntegerField(
        null=True,
        blank=True,
        validators=[
            validators.MinValueValidator(MIN_AGE_VALUE),
            validators.MaxValueValidator(MAX_AGE_VALUE),
        ],
    )
    profile_picture = models.ImageField(
        upload_to='profile_pictures/',
        null=True,
        blank=True,
    )
    delivery_address = models.CharField(
        max_length=DELIVERY_ADDRESS_MAX_LEN,
        null=True,
        blank=True,
        validators=[
            validators.MinLengthValidator(DELIVERY_ADDRESS_MIN_LEN),
        ],
    )

    def __str__(self):
        return self.username

    def get_total_comments(self):
        return self.bookreview_set.count()


class Book(models.Model):
    TITLE_MAX_LEN = 200
    TITLE_MIN_LEN = 2

    AUTHOR_NAME_MAX_LEN = 100
    AUTHOR_NAME_MIN_LEN = 2

    CATEGORIES = (
        ("Children's literature", "Children's literature"),
        ("Fiction", "Fiction"),
        ("Historical Fiction", "Historical Fiction"),
        ("Science Fiction", "Science Fiction"),
        ("Mystery", "Mystery"),
        ("Memoir", "Memoir"),
        ("Thriller", "Thriller"),
        ("Humor", "Humor"),
        ("Romance novel", "Romance novel"),
        ("Non-fiction", "Non-fiction"),
    )

    title = models.CharField(
        max_length=TITLE_MAX_LEN,
        validators=[
            validators.MinLengthValidator(TITLE_MIN_LEN),
        ],
        null=False,
        blank=False,
    )

    category = models.CharField(
        max_length=50,
        choices=CATEGORIES,
        null=False,
        blank=False,
    )

    author = models.CharField(
        max_length=AUTHOR_NAME_MAX_LEN,
        validators=[
            validators.MinLengthValidator(AUTHOR_NAME_MIN_LEN),
        ],
        null=False,
        blank=False,
    )
    description = models.TextField(
        null=False,
        blank=False,

    )

    pages = models.IntegerField(
        default=1,
        null=False,
        blank=False,
    )

    price = models.DecimalField(
        max_digits=6,
        decimal_places=2,
        null=False,
        blank=False,
        default=0,
    )
    cover_image = models.ImageField(
        upload_to='media/book_covers/',
        null=False,
        blank=False,
    )
    featured = models.BooleanField(default=False)

    def __str__(self):
        return self.title


class BookReview(models.Model):
    book = models.ForeignKey(
        'Book',
        on_delete=models.CASCADE,
        related_name='reviews',
        null=False,
        blank=False,
    )
    user = models.ForeignKey(
        'book.Customer',
        on_delete=models.CASCADE,
        null=False,
        blank=False,
    )
    review_text = models.TextField(
        null=False,
        blank=False,
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        null=False,
        blank=False,
    )
    updated_at = models.DateTimeField(
        auto_now=True,
        null=False,
        blank=False,
    )

    def __str__(self):
        return f"Review by {self.user.username} for {self.book.title}"

    # For sorting the reviews
    class Meta:
        ordering = ['-created_at']

online_bookstore/apps/book/views.py
# book/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.views import (
    LoginView, LogoutView, PasswordChangeView
)
from django.db.models import Count, Q
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import (
    DeleteView, ListView, TemplateView, UpdateView
)
# Local imports
from .custom_mixins import AnonymousRequiredMixin, CustomPermissionDeniedMixin
from .forms import (
    BookPublishForm, CustomPasswordChangeForm,
    OrderUpdateForm, RegistrationForm, ReviewForm, UserProfileForm
)
from .models import Book, BookReview, Customer
from ..store.models import Order


class RegisterView(AnonymousRequiredMixin, View):
    template_name = 'registration/register.html'
    success_url = reverse_lazy('home-page')

    def get(self, request):
        form = RegistrationForm()

        context = {
            'form': form
        }

        return render(request, self.template_name, context)

    def post(self, request):
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()

            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']

            # Authenticate the user and log them in
            user = authenticate(request, username=username, password=password)
            if user:
                login(request, user)

            return redirect(self.success_url)

        context = {
            'form': form
        }

        return render(request, self.template_name, context)


class LoginUserView(AnonymousRequiredMixin, LoginView):
    template_name = 'registration/login.html'

    def form_invalid(self, form):
        # Add a custom error message to the form
        form.add_error(None, "Incorrect username or password. Please try again.")
        return super().form_invalid(form)


class LogoutUserView(LogoutView):
    next_page = 'home-page'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class HomePageView(TemplateView):
    template_name = 'common/home-page.html'

    def get(self, request, *args, **kwargs):
        featured_books = Book.objects.filter(featured=True)

        context = {
            'featured_books': featured_books
        }

        return render(request, self.template_name, context)


class ProfilePageView(CustomPermissionDeniedMixin, LoginRequiredMixin, View):
    NO_ACCESS_ERROR_MSG = 'Please log in to view this page.'
    SUCCESS_MESSAGE = 'Your profile has been updated successfully.'

    def get(self, request):
        user = request.user
        total_comments = user.get_total_comments()
        form = UserProfileForm(instance=user)

        context = {
            'form': form,
            'total_comments': total_comments,
        }

        return render(request, 'common/profile.html', context)

    def post(self, request):
        user = request.user
        total_comments = user.get_total_comments()
        form = UserProfileForm(request.POST, request.FILES, instance=user)

        if form.is_valid():
            form.save()
            messages.success(request, self.SUCCESS_MESSAGE)
        else:
            # Pass cleaned_data to the context to display in case of an invalid form submission
            context = {
                'form': form,
                'total_comments': total_comments,
                'cleaned_data': form.cleaned_data,
            }
            return render(request, 'common/profile.html', context)

        context = {
            'form': form,
            'total_comments': total_comments,
        }

        return render(request, 'common/profile.html', context)


class CustomPasswordChangeView(CustomPermissionDeniedMixin, PasswordChangeView):
    template_name = 'registration/password-change-page.html'
    success_url = reverse_lazy('password-change-done')
    form_class = CustomPasswordChangeForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class AboutUsView(TemplateView):
    template_name = 'common/about-us.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        staff_members = Customer.objects.filter(is_staff=True)
        superusers = Customer.objects.filter(is_superuser=True)
        context['staff_members'] = staff_members
        context['superusers'] = superusers
        return context


class MyOrdersView(CustomPermissionDeniedMixin, LoginRequiredMixin, View):
    NO_ACCESS_ERROR_MSG = 'Please log in to view this page.'

    template_name = 'common/my-orders.html'

    def get(self, request):
        orders = Order.objects.filter(user=request.user)

        context = {
            'orders': orders
        }
        return render(request, self.template_name, context)


# Reviewed but queryset method needs studying
class CataloguePageView(ListView):
    model = Book
    template_name = 'common/catalogue-page.html'
    context_object_name = 'books'
    paginate_by = 16

    def get_queryset(self):
        queryset = super().get_queryset()
        search_query = self.request.GET.get('search_query')

        if search_query:
            # Use Q objects to perform case-insensitive search on author, title, and category
            queryset = queryset.filter(
                Q(author__icontains=search_query) |
                Q(title__icontains=search_query) |
                Q(category__icontains=search_query)
            )

        return queryset.order_by('-price')


class BookDetailView(View):
    template_name = 'books/book-detail.html'

    @staticmethod
    def get_book_and_reviews(pk):  # Utility method for fetching books and reviews
        book = get_object_or_404(Book, pk=pk)
        reviews = book.reviews.order_by('-created_at')
        return book, reviews

    def get(self, request, pk):
        book, reviews = self.get_book_and_reviews(pk)
        review_form = ReviewForm()

        context = {
            'book': book,
            'reviews': reviews,
            'review_form': review_form,
        }

        return render(request, self.template_name, context)

    def post(self, request, pk):
        book, reviews = self.get_book_and_reviews(pk)
        review_form = ReviewForm(request.POST)

        if review_form.is_valid():
            review = review_form.save(commit=False)
            review.user = request.user
            review.book = book
            review.save()
            return redirect('book-detail', pk=pk)

        context = {
            'book': book,
            'reviews': reviews,
            'review_form': review_form,
        }

        return render(request, self.template_name, context)


# Reviewed Visit again
class EditReviewView(LoginRequiredMixin, UpdateView):
    template_name = 'books/edit-review.html'
    model = BookReview
    form_class = ReviewForm

    def get_success_url(self):
        review = self.object
        kwargs = {
            'pk': review.book.pk
        }
        return reverse_lazy('book-detail', kwargs=kwargs)

    def get_object(self, queryset=None):
        review_id = self.kwargs.get('review_id')
        return get_object_or_404(BookReview, id=review_id, user=self.request.user)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['review_id'] = self.kwargs.get('review_id')
        return kwargs


class PublishBookView(CustomPermissionDeniedMixin, LoginRequiredMixin, UserPassesTestMixin, View):
    template_name = 'for_staff/publish-book.html'
    form_class = BookPublishForm
    NO_ACCESS_ERROR_MSG = 'You need staff privileges to publish a book.'

    def test_func(self):
        return self.request.user.is_staff

    def get(self, request):
        form = self.form_class()
        context = {
            'form': form,
        }
        return render(request, self.template_name, context)

    def post(self, request):
        form = self.form_class(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('home-page')

        context = {
            'form': form,
        }
        return render(request, self.template_name, context)


class DeleteBookView(CustomPermissionDeniedMixin, LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    template_name = 'for_staff/confirm-delete.html'
    model = Book
    success_url = reverse_lazy('catalogue-page')
    NO_ACCESS_ERROR_MSG = 'You need staff privileges to delete a book.'

    def test_func(self):
        return self.request.user.is_staff


class EditBookView(CustomPermissionDeniedMixin, LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    template_name = 'for_staff/edit-book.html'
    model = Book
    form_class = BookPublishForm
    NO_ACCESS_ERROR_MSG = 'You need staff privileges to edit a book.'

    def get_success_url(self):
        kwargs = {
            'pk': self.object.pk
        }
        return reverse_lazy('book-detail', kwargs=kwargs)

    def test_func(self):
        return self.request.user.is_staff


class UserListView(CustomPermissionDeniedMixin, LoginRequiredMixin, UserPassesTestMixin, ListView):
    template_name = 'for_staff/user-list.html'
    model = Customer
    context_object_name = 'users'
    NO_ACCESS_ERROR_MSG = 'You are not allowed to view this page.'

    def test_func(self):
        return self.request.user.is_staff

    def get_queryset(self):
        queryset = super().get_queryset().annotate(
            total_orders=Count('orders', distinct=True),
            total_reviews=Count('bookreview', distinct=True)
        )

        return queryset.order_by('username')

templates/books/book-detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="container mt-4">
        <h1>{{ book.title }} by <span style="text-decoration: underline">{{ book.author }}</span></h1>

        <hr>

        <div class="row">
            <div class="col-md-6">
                <img src="{{ book.cover_image.url }}" class="card-img-top custom-card-size" alt="Book Cover">
            </div>
            <div class="col-md-6">
                <div class="row">
                    {% if user.is_authenticated and user.is_staff %}
                        <div class="col-lg-6 mb-3">
                            <a href="{% url 'delete-book' pk=book.pk %}" class="btn btn-danger btn-lg btn-block">Delete
                                Book</a>
                        </div>
                        <div class="col-lg-6 mb-3">
                            <a href="{% url 'edit-book' pk=book.pk %}" class="btn btn-secondary btn-lg btn-block">Edit
                                Book</a>
                        </div>
                    {% endif %}
                    <div class="col-lg-12">
                        <form style="background-color: transparent; box-shadow: none;" method="post"
                              action="{% url 'add-to-cart' pk=book.pk %}">
                            {% csrf_token %}
                            {% if user.is_authenticated %}
                                <button type="submit" class="btn btn-primary btn-lg btn-block">
                                    <i class="fas fa-shopping-cart"></i> Add to Cart
                                </button>
                            {% endif %}
                        </form>
                    </div>
                </div>
                <hr>
                <p class="card-text font-weight-bold text-danger">Price: ${{ book.price }}</p>
                <hr>
                <h1 class="mb-3">{{ book.title }} - {{ book.category }}</h1>
                <p class="text-dark"><strong>Pages: {{ book.pages }}</strong></p>
                <hr>
                <h2>Plot Summary</h2>
                {% if user.is_authenticated and user.is_staff %}
                {% endif %}
                <div class="book-description">
                    {% if book.description|length > 1000 %}

                        {# Show more / show less functionality starts here #}
                        <div class="description-truncate">
                            <p class="mb-4">{{ book.description|truncatechars:1000 }}
                                <button class="btn btn-link show-more-btn">Show More...</button>
                            </p>
                        </div>
                        <div class="description-full" style="display: none;">
                            <p class="mb-4">{{ book.description }}
                                <button class="btn btn-link show-less-btn">Show Less...</button>
                            </p>
                        </div>
                        {# Show more / show less functionality ends here #}

                    {% else %}
                        <p class="mb-4">{{ book.description }}</p>
                    {% endif %}
                </div>
            </div>
        </div>
        <hr>
        <h2>Reader Reviews</h2>
        <hr>
        {% for review in book.reviews.all %}
            <div class="card mb-3">
                <div class="card-body">
                    <strong>
                        {{ review.user.username }}
                    </strong>
                    <p>
                        Created on: {{ review.created_at|date:"F d, Y" }}
                        {% if review.updated_at > review.created_at %}
                            <span class="edited-indicator" data-toggle="tooltip"
                                  title="Edited on {{ review.updated_at|date:"F d, Y" }}">
                                  <strong>(edited)</strong>
                            </span>
                        {% endif %}
                    </p>
                    <hr>
                    {% if review.review_text|length > 500 %}
                        <div class="description-truncate mb-4">
                            {{ review.review_text|truncatechars:500 }}
                            <button class="btn btn-link show-more-btn">Show More...</button>
                        </div>
                        <div class="description-full" style="display: none;">
                            {{ review.review_text }}
                            <button class="btn btn-link show-less-btn">Show Less...</button>
                        </div>
                    {% else %}
                        <div class="mb-4">{{ review.review_text }}</div>
                    {% endif %}
                    <hr>
                    {% if user.is_authenticated %}
                        {% if user == review.user %}
                            <a href="#" class="btn btn-link edit-review-btn" data-review-id="{{ review.id }}"><i
                                    class="fas fa-pencil-alt"></i> Edit
                                Review</a>

                        {% endif %}
                    {% endif %}
                </div>
            </div>
        {% empty %}
            <p>No reviews yet. Be the first to write one!</p>
        {% endfor %}
        {% if user.is_authenticated %}
            <hr>
            <h2>Write a Review</h2>
            <form method="post" class="mt-3 custom-form" style="width: 100%">
                {% csrf_token %}
                {{ review_form.as_p }}
                <button type="submit" class="btn btn-primary">Submit Review</button>
            </form>
        {% else %}
            <div class="alert alert-info mt-3">
                <p>Please <a href="{% url 'login' %}">login</a> to write a review.</p>
            </div>
        {% endif %}
    </div>

    <script src="{% static 'js/book-detail.js' %}"></script>

{% endblock %}

templates/books/book_detail.html
<!-- book_detail.html -->

{% extends 'base.html' %}

{% block content %}
    <div class="container mt-4">
        <div class="row">
            <div class="col-md-6">
                <img src="{{ book.cover_image.url }}" class="card-img-top custom-card-size" alt="Book Cover">
            </div>
            <div class="col-md-6">
                <a href="{% url 'process_order' pk=book.pk %}" class="btn btn-primary btn-lg">Buy Now</a>
                <hr>
                <p class="card-text">Price: ${{ book.price }}</p>
                <hr>
                <h1 class="mb-3">{{ book.title }} </h1>
                <p class="text-muted">By {{ book.author }}</p>
                <hr>
                <div class="book-description">
                    {% if book.description|length > 1000 %}
                        <div class="description-truncate">

                            <p class="mb-4">{{ book.description|truncatechars:1000 }}
                                <button class="btn btn-link show-more-btn">Show More...</button>
                            </p>
                        </div>
                        <div class="description-full" style="display: none;">
                            <p class="mb-4">{{ book.description }}
                                <button class="btn btn-link show-less-btn">Show Less...</button>
                            </p>

                        </div>
                    {% else %}
                        <p class="mb-4">{{ book.description }}</p>
                    {% endif %}
                </div>

            </div>
        </div>

        <hr>

        <h2>Reader Reviews</h2>
        {% for review in book.reviews.all %}
            <div class="card mb-3">
                <div class="card-body">
                    <strong>
                        {{ review.user.username }}
                    </strong>
                    <p>
                        {{ review.created_at }}
                    </p>
                    <hr>
                    <p class="card-text">
                        {% if review.review_text|length > 500 %}
                            <div class="description-truncate">
                                <p class="mb-4">{{ review.review_text|truncatechars:500 }}
                                    <button class="btn btn-link show-more-btn">Show More...</button>
                                </p>
                            </div>
                            <div class="description-full" style="display: none">
                                <p class="mb-4">{{ review.review_text }}
                                    <button class="btn btn-link show-less-btn">Show Less...</button>
                                </p>
                            </div>
                        {% endif %}
                    </p>
                </div>
            </div>
        {% empty %}
            <p>No reviews yet. Be the first to write one!</p>
        {% endfor %}

        {% if user.is_authenticated %}
            <hr>
            <h2>Write a Review</h2>
            <form method="post" class="mt-3 custom-form-style">
                {% csrf_token %}
                {{ review_form.as_p }}
                <button type="submit" class="btn btn-primary">Submit Review</button>
            </form>
        {% else %}
            <div class="alert alert-info mt-3">
                <p>Please <a href="{% url 'login' %}">login</a> to write a review.</p>
            </div>
        {% endif %}
    </div>
{% endblock %}

templates/books/edit-review.html
{% extends 'base.html' %}

{% block content %}
    <h2>Edit Review</h2>
    <form method="post" class="mt-3 custom-form" style="width: 50%">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Save Changes</button>
    </form>
{% endblock %}

templates/books/order_form.html
<!-- order_form.html -->
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <div class="row mt-4">
            <div class="col-md-6">

                <h2 class="mt-4">Shipping Information</h2>
                <form method="post">
                    {% csrf_token %}
                    {{ shipping_info_form.as_p }}
                    <button type="submit" class="btn btn-primary">Place Order</button>
                </form>
            </div>
            <div class="col-md-6">
                <a href="{% url 'home-page' %}" class="btn btn-primary">Back to the Store</a>
                <h2 class="mt-4">Order Summary</h2>
                <div class="card mb-3" style="max-width: 540px;">
                    <div class="row g-0">
                        <div class="col-md-4">
                            <img src="{{ book.cover_image.url }}" class="card-img-top card-img-big" alt="Book Cover">
                        </div>
                        <div class="col-md-8">
                            <div class="card-body">
                                <hr>
                                <h5 class="card-title">{{ book.title }}</h5>
                                <hr>
                                <p class="card-text">Author: {{ book.author }}</p>
                                <hr>
                                <p class="card-text">Price: ${{ book.price }}</p>
                                <hr>
                                <a href="{% url 'book_detail' pk=book.pk %}" class="btn btn-primary">Details</a>
                                <hr>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/books/publish_book.html
{#<!-- publish_book.html -->#}
{#{% extends 'base.html' %}#}
{#{% block content %}#}
{#    <div class="container mt-4">#}
{#        <h2 class="mb-4">Publish Book</h2>#}
{#        <form method="post" enctype="multipart/form-data">#}
{#            {% csrf_token %}#}
{#            <div class="form-group">#}
{#                <label for="id_title">Title:</label>#}
{#                <input type="text" name="title" id="id_title" class="form-control">#}
{#            </div>#}
{#            <div class="form-group">#}
{#                <label for="id_category">Category:</label>#}
{#                <select name="category" id="id_category" class="form-control">#}
{#                    <option value="Children's literature">Children's literature</option>#}
{#                    <option value="Fiction">Fiction</option>#}
{#                    <option value="Historical Fiction">Historical Fiction</option>#}
{#                    <option value="Science fiction">Science fiction</option>#}
{#                    <option value="Mystery">Mystery</option>#}
{#                    <option value="Memoir">Memoir</option>#}
{#                    <option value="Thriller">Thriller</option>#}
{#                    <option value="Humor">Humor</option>#}
{#                    <option value="Romance novel">Romance novel</option>#}
{##}
{#                </select>#}
{#            </div>#}
{#            <div class="form-group">#}
{#                <label for="id_author">Author:</label>#}
{#                <input type="text" name="author" id="id_author" class="form-control">#}
{#            </div>#}
{#            <div class="form-group">#}
{#                <label for="id_description">Description:</label>#}
{#                <textarea name="description" id="id_description" class="form-control" rows="4"></textarea>#}
{#            </div>#}
{#            <div class="form-group">#}
{#                <label for="id_price">Price:</label>#}
{#                <input type="number" name="price" id="id_price" class="form-control">#}
{#            </div>#}
{#            <div class="form-group">#}
{#                <label for="id_cover_image">Cover Image:</label>#}
{#                <input type="file" name="cover_image" id="id_cover_image" class="form-control-file">#}
{#            </div>#}
{#            <div class="form-check mb-3">#}
{#                <input type="checkbox" name="featured" id="id_featured" class="form-check-input">#}
{#                <label class="form-check-label" for="id_featured">Featured</label>#}
{#            </div>#}
{#            <button type="submit" class="btn btn-primary">Publish</button>#}
{#        </form>#}
{#    </div>#}
{#{% endblock %}#}


<!-- publish_book.html -->
{% extends 'base.html' %}
{% block content %}

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary mt-3">Publish Book</button>
    </form>
{% endblock %}