online_bookstore/urls.py
# project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.core.mail import send_mail
from django.urls import path, include
from online_bookstore.apps.book.views import Custom404View

handler404 = Custom404View.as_view()

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('online_bookstore.apps.book.urls')),
    path('', include('online_bookstore.apps.store.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# send_mail(
#     subject='Registration successful',
#     message='Hello',
#     from_email='greetings@emporium.com',
#     recipient_list=('nikolaycholakovdemo@gmail.com', )
# )

online_bookstore/apps/book/models.py
# book/models.py

from django.contrib.auth.models import User, AbstractUser
from django.core import validators
from django.db import models


class Customer(AbstractUser):
    NAME_MAX_LEN = 30
    NAME_MIN_LEN = 2

    EMAIL_MAX_LEN = 50
    DELIVERY_ADDRESS_MIN_LEN = 10
    DELIVERY_ADDRESS_MAX_LEN = 250

    MIN_AGE_VALUE = 1
    MAX_AGE_VALUE = 150

    email = models.EmailField(
        max_length=EMAIL_MAX_LEN,
        unique=True,
        null=True,
        validators=[
            validators.EmailValidator()
        ]
    )
    age = models.PositiveIntegerField(
        null=True,
        blank=True,
        validators=[
            validators.MinValueValidator(MIN_AGE_VALUE),
            validators.MaxValueValidator(MAX_AGE_VALUE),
        ],
    )
    profile_picture = models.ImageField(
        upload_to='profile_pictures/',
        null=True,
        blank=True,
    )
    delivery_address = models.CharField(
        max_length=DELIVERY_ADDRESS_MAX_LEN,
        null=True,
        blank=True,
        validators=[
            validators.MinLengthValidator(DELIVERY_ADDRESS_MIN_LEN),
        ],
    )

    def __str__(self):
        return self.username

    def get_total_comments(self):
        return self.bookreview_set.count()


class Book(models.Model):
    TITLE_MAX_LEN = 200
    TITLE_MIN_LEN = 2

    AUTHOR_NAME_MAX_LEN = 100
    AUTHOR_NAME_MIN_LEN = 2

    CATEGORIES = (
        ("Children's literature", "Children's literature"),
        ("Fiction", "Fiction"),
        ("Historical Fiction", "Historical Fiction"),
        ("Science Fiction", "Science Fiction"),
        ("Mystery", "Mystery"),
        ("Memoir", "Memoir"),
        ("Thriller", "Thriller"),
        ("Humor", "Humor"),
        ("Romance novel", "Romance novel"),
        ("Non-fiction", "Non-fiction"),
    )

    title = models.CharField(
        max_length=TITLE_MAX_LEN,
        validators=[
            validators.MinLengthValidator(TITLE_MIN_LEN),
        ],
        null=False,
        blank=False,
    )

    category = models.CharField(
        max_length=50,
        choices=CATEGORIES,
        null=False,
        blank=False,
    )

    author = models.CharField(
        max_length=AUTHOR_NAME_MAX_LEN,
        validators=[
            validators.MinLengthValidator(AUTHOR_NAME_MIN_LEN),
        ],
        null=False,
        blank=False,
    )
    description = models.TextField(
        null=False,
        blank=False,

    )

    pages = models.IntegerField(
        default=1,
        null=False,
        blank=False,
    )

    price = models.DecimalField(
        max_digits=6,
        decimal_places=2,
        null=False,
        blank=False,
        default=0,
    )
    cover_image = models.ImageField(
        upload_to='media/book_covers/',
        null=False,
        blank=False,
    )
    featured = models.BooleanField(default=False)

    def __str__(self):
        return self.title


class BookReview(models.Model):
    book = models.ForeignKey(
        'Book',
        on_delete=models.CASCADE,
        related_name='reviews',
        null=False,
        blank=False,
    )
    user = models.ForeignKey(
        'book.Customer',
        on_delete=models.CASCADE,
        null=False,
        blank=False,
    )
    review_text = models.TextField(
        null=False,
        blank=False,
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        null=False,
        blank=False,
    )
    updated_at = models.DateTimeField(
        auto_now=True,
        null=False,
        blank=False,
    )

    def __str__(self):
        return f"Review by {self.user.username} for {self.book.title}"

    # For sorting the reviews
    class Meta:
        ordering = ['-created_at']

online_bookstore/apps/store/models.py
# store/models.py

from django.db import models

from online_bookstore.apps.book.models import Book, Customer


class BaseModel(models.Model):
    book = models.ForeignKey(
        Book,
        on_delete=models.CASCADE,
    )
    quantity = models.PositiveIntegerField(
        default=1,
    )
    price = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        default=0,
    )

    def __str__(self):
        return f"{self.quantity} x {self.book.title}"

    def get_total(self):
        total = self.book.price * self.quantity
        return total

    class Meta:
        abstract = True


class Order(models.Model):
    ORDER_STATUS = (
        ('Pending', 'Pending'),
        ('Processing', 'Processing'),
        ('Shipped', 'Shipped'),
        ('Delivered', 'Delivered'),
        ('Cancelled', 'Cancelled'),
    )

    user = models.ForeignKey(
        Customer,
        on_delete=models.CASCADE,
        related_name='orders'
    )
    order_date = models.DateTimeField(
        auto_now_add=True
    )
    status = models.CharField(
        max_length=20,
        choices=ORDER_STATUS,
        default='Pending'
    )

    def total_items(self):
        return self.orderitem_set.count()

    def total_price(self):
        return sum(item.get_total() for item in self.orderitem_set.all())

    def __str__(self):
        return f"Order #{self.id}"


class OrderItem(BaseModel):
    order = models.ForeignKey(
        Order,
        on_delete=models.CASCADE,
    )


class Cart(models.Model):
    user = models.ForeignKey(
        Customer,
        on_delete=models.CASCADE,
        related_name='cart'
    )

    def total_price(self):
        return sum(item.get_total() for item in self.cartitem_set.all())

    def total_items(self):
        return sum(item.quantity for item in self.cartitem_set.all())

    def __str__(self):
        return f"Cart for {self.user}"


class CartItem(BaseModel):
    cart = models.ForeignKey(
        Cart,
        on_delete=models.CASCADE,
    )

templates/common/about-us.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <section class="about-us my-5">
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <h2 class="mb-4">About Us</h2>
                    <hr>
                    <p>Welcome to <strong>The Bookstack Emporium</strong>, where a world of stories awaits you. Our
                        passion
                        for books
                        and the art of reading drives us to provide you with a unique literary experience.</p>
                    <p>At The Bookstack Emporium, we believe that books have the power to transform, inspire, and
                        connect.
                        Our goal is
                        to curate a diverse collection of books that cater to different tastes, genres, and moods.</p>
                    <p>Our team is composed of dedicated readers, writers, and technology enthusiasts who are committed
                        to
                        creating a community where book lovers can explore, discuss, and share their love for
                        literature.</p>
                    <p>Join us in celebrating the magic of books and embark on a journey of endless imagination and
                        discovery.</p>
                </div>
            </div>
        </div>
    </section>

    <section class="mission bg-light py-5">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-8 text-center">
                    <h2 class="mb-4">Our Mission</h2>
                    <hr>
                    <p class="lead">At The Bookstack Emporium, our mission is to:</p>
                    <ul class="list-unstyled">
                        <li>Provide a platform for readers to discover and explore a wide range of books.</li>
                        <li>Foster a vibrant community of book enthusiasts to engage in meaningful discussions and share
                            their insights.
                        </li>
                        <li>Promote diverse voices and perspectives in literature.</li>
                        <li>Offer a seamless and enjoyable shopping experience for book lovers.</li>
                    </ul>
                </div>
            </div>
        </div>
    </section>

    <section class="contact-us my-5">
        <div class="container">
            <h2 class="text-center mb-4">Contact Us</h2>
            <hr>
            <div class="row justify-content-center">
                <div class="col-lg-6">
                    <ul class="list-unstyled">
                        <li><strong>Email:</strong> contact@bookstackemporium.com</li>
                        <li><strong>Phone:</strong> +1 (123) 456-7890</li>
                        <li><strong>Address:</strong> 123 Bookshelf Street, Literary Town, Bookland</li>
                        <li>
                        <hr>

                            <iframe src="https://www.google.com/maps/embed?pb=!1m16!1m12!1m3!1d2073.4798475047455!2d23.320115659679498!3d42.69645070763487!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!2m1!1ssofia%20city%20center!5e0!3m2!1sen!2sbg!4v1691346746830!5m2!1sen!2sbg"
                                    width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy"
                                    referrerpolicy="no-referrer-when-downgrade"></iframe>
                        </li>
                    </ul>
                </div>

            </div>
        </div>
    </section>

    <section class="terms-of-service bg-light py-5">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-8 text-center">
                    <h2 class="mb-4">Terms of Service</h2>
                    <hr>
                    <p>Welcome to Bookstack Emporium! By using our website, you agree to the following terms:</p>
                    <ul class="list-unstyled">
                        <li>Content: All content on our site is for informational and entertainment purposes only.</li>
                        <li>Privacy: We value your privacy and handle your personal data responsibly. Review our Privacy
                            Policy.
                        </li>
                        <li>Reviews: Users can submit book reviews, which must be respectful and follow community
                            guidelines.
                        </li>
                        <li>Orders: Book purchases are subject to availability and our refund policy.</li>
                    </ul>
                </div>
            </div>
        </div>
    </section>

    <section class="py-5">
    <div class="container">
        <h2 class="text-center mb-5">Meet Our Team</h2>
        <div class="row justify-content-center">
            {% for staff_member in staff_members %}
                {% if staff_member not in superusers %}
                    <div class="col-md-4 mb-4">
                        <div class="card text-center shadow">
                            {% if staff_member.profile_picture %}
                                <div class="card-img-top rounded-circle mx-auto d-block mt-4" style="width: 100px; height: 100px; overflow: hidden;">
                                    <img src="{{ staff_member.profile_picture.url }}"
                                         alt="{{ staff_member.username }}"
                                         class="img-fluid" style="object-fit: cover;">
                                </div>
                            {% else %}
                                <div class="card-img-top rounded-circle mx-auto d-block mt-4" style="width: 100px; height: 100px; overflow: hidden;">
                                    <img src="{% static 'images/default_profile_picture.svg' %}"
                                         alt="Default Profile"
                                         class="img-fluid" style="object-fit: cover;">
                                </div>
                            {% endif %}
                            <div class="card-body">
                                <h5 class="card-title">{{ staff_member.get_full_name }}</h5>
                                <p class="card-text text-muted">{{ staff_member.email }}</p>
                                <p class="card-text text-muted">Staff</p>
                            </div>
                        </div>
                    </div>
                {% endif %}
            {% endfor %}

            {% for superuser in superusers %}
                <div class="col-md-4 mb-4">
                    <div class="card text-center shadow">
                        {% if superuser.profile_picture %}
                            <div class="card-img-top rounded-circle mx-auto d-block mt-4" style="width: 100px; height: 100px; overflow: hidden;">
                                <img src="{{ superuser.profile_picture.url }}" alt="{{ superuser.username }}"
                                     class="img-fluid" style="object-fit: cover;">
                            </div>
                        {% else %}
                            <div class="card-img-top rounded-circle mx-auto d-block mt-4" style="width: 100px; height: 100px; overflow: hidden;">
                                <img src="{% static 'images/default_profile_picture.svg' %}"
                                     alt="Default Profile"
                                     class="img-fluid" style="object-fit: cover;">
                            </div>
                        {% endif %}
                        <div class="card-body">
                            <h5 class="card-title">{{ superuser.get_full_name }}</h5>
                            <p class="card-text text-muted">{{ superuser.email }}</p>
                            <p class="card-text text-muted">CEO</p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</section>
{% endblock %}

templates/common/catalogue-page.html
{% extends 'base.html' %}

{% block content %}
    <div class="container mt-4">
        <h2>Books Catalogue</h2>
        <hr>
        <div class="row">
            <div class="col-md-6">
                <form method="GET" style="width: 100%" class="form-inline">
                    <input type="text" name="search_query" style="width: 100%" class="form-control mr-sm-2"
                           placeholder="Search by author, title, or category" aria-label="Search"
                           value="{{ request.GET.search_query }}">
                    <button type="submit" class="btn btn-outline-primary my-2 my-sm-0">Search &#x2192;</button>
                    {% if request.GET.search_query %}
                        <a href="{% url 'catalogue-page' %}" class="btn btn-secondary ml-2">Clear Search</a>
                    {% endif %}
                </form>
            </div>
        </div>
        <hr>
        <div class="mt-4" id="pagination">
            {% if is_paginated %}
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?search_query={{ request.GET.search_query }}&page=1">&laquo;
                                first</a>
                        </li>
                        <li class="page-item">
                            <a class="page-link"
                               href="?search_query={{ request.GET.search_query }}&page={{ page_obj.previous_page_number }}">previous</a>
                        </li>
                    {% endif %}

                    <!-- Current page number and total pages -->
                    <li class="page-item disabled">
                        <span class="page-link">{{ page_obj.number }} / {{ page_obj.paginator.num_pages }}</span>
                    </li>

                    {% if page_obj.has_next %}
                        <li class="page-item">
                            <a class="page-link"
                               href="?search_query={{ request.GET.search_query }}&page={{ page_obj.next_page_number }}">next</a>
                        </li>
                        <li class="page-item">
                            <a class="page-link"
                               href="?search_query={{ request.GET.search_query }}&page={{ page_obj.paginator.num_pages }}">last
                                &raquo;</a>
                        </li>
                    {% endif %}
                </ul>
            {% endif %}
        </div>

        <hr>
        <div class="row">
            {% for book in books %}
                <div class="col-md-3 mb-4">
                    <div class="card h-100">
                        <img src="{{ book.cover_image.url }}" class="card-img-top" alt="Book Cover"
                             style="width: 253px; height: 350px;">
                        <div class="card-body">
                            <h5 style="height: 3rem" class="card-title">{{ book.title }}</h5>
                            <hr>

                            <p class="card-text">By {{ book.author }}</p>
                            <p class="card-text font-weight-bold text-danger">Price: ${{ book.price }}</p>

                            <hr>

                            <div class="btn-container">
                                <div class="row">
                                    <div class="col-6">
                                        <a href="{% url 'book-detail' pk=book.pk %}" style="background-color: #007bff"
                                           class="btn btn-primary btn-sm">Details</a>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-12">
                                        <form style="width: 100%; background-color: transparent; box-shadow: none;"
                                              method="post"
                                              action="{% url 'add-to-cart' pk=book.pk %}">
                                            {% csrf_token %}
                                            <button type="submit" class="btn btn-primary btn-sm btn-block">
                                                <i class="fas fa-shopping-cart mr-2"></i> Add to Cart
                                            </button>
                                        </form>
                                    </div>
                                </div>
                            </div>


                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        <hr>
        <div class="mt-4" id="pagination">
            {% if is_paginated %}
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?search_query={{ request.GET.search_query }}&page=1">&laquo;
                                first</a>
                        </li>
                        <li class="page-item">
                            <a class="page-link"
                               href="?search_query={{ request.GET.search_query }}&page={{ page_obj.previous_page_number }}">previous</a>
                        </li>
                    {% endif %}

                    {% if page_obj.has_next %}
                        <li class="page-item">
                            <a class="page-link"
                               href="?search_query={{ request.GET.search_query }}&page={{ page_obj.next_page_number }}">next</a>
                        </li>
                        <li class="page-item">
                            <a class="page-link"
                               href="?search_query={{ request.GET.search_query }}&page={{ page_obj.paginator.num_pages }}">last
                                &raquo;</a>
                        </li>
                    {% endif %}
                </ul>
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/common/my-orders.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="container mt-4">
        <div class="d-flex justify-content-between align-items-center">
            <h2>My Orders</h2>
            <div>
                <a href="{% url 'catalogue-page' %}" class="btn btn-primary">&#x2190; Back to the catalogue</a>
                <a href="{% url 'profile-page' %}" class="btn btn-primary">&#x2190; Back to the profile page</a>
            </div>
        </div>
        <hr>
        {% if orders %}
            <table class="table table-bordered" id="orders-table">
                <thead>
                <tr>
                    <th class="text-center sortable" data-sort="status">Status</th>
                    <th class="text-center sortable" data-sort="date">Date Order</th>
                    <th class="text-center sortable" data-sort="items">Total Items</th>
                    <th class="text-center sortable" data-sort="price">Total Price</th>
                </tr>
                </thead>
                <tbody>
                {% for order in orders %}
                    <tr>
                        <td class="text-center"
                            data-status="{{ order.get_status_display }}">{{ order.get_status_display }}</td>
                        <td class="text-center">{{ order.order_date }}</td>
                        <td class="text-center">{{ order.total_items }}</td>
                        <td class="text-center">${{ order.total_price }}</td>
                    </tr>
                {% endfor %}
                </tbody>
                <tfoot>
                <tr>
                    <td colspan="4" class="text-center">
                        <strong>Total Orders: {{ orders|length }}</strong>
                    </td>
                </tr>
                </tfoot>
            </table>
        {% else %}
            <p class="text-center">No orders found.</p>
        {% endif %}
    </div>

    <script src="{% static 'js/my-orders-page.js' %}">

    </script>
{% endblock %}

templates/common/profile.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load static %}
{% block content %}
    <div class="container mt-4">

        <h2>{{ user.username }}</h2>
        <hr>


        <br>
        {% if messages %}
            <div class="messages">
                {% for message in messages %}
                    <div class="alert alert-success mt-3">{{ message }}</div>
                {% endfor %}
            </div>
        {% endif %}
        <div class="row">
            <div class="col-md-6">

                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <h5>Edit Profile Information</h5>
                    <hr>

                    <div class="form-group">
                        <label for="{{ form.username.id_for_label }}">Username:</label>
                        {{ form.username|add_class:"form-control" }}
                        {% if form.username.errors %}
                            <div class="text-danger">{{ form.username.errors.as_text }}</div>
                        {% endif %}
                    </div>

                    <div class="form-group">
                        <label for="{{ form.first_name.id_for_label }}">First Name:</label>
                        {{ form.first_name|add_class:"form-control" }}
                        {% if form.first_name.errors %}
                            <div class="text-danger">{{ form.first_name.errors.as_text }}</div>
                        {% endif %}
                    </div>

                    <div class="form-group">
                        <label for="{{ form.last_name.id_for_label }}">Last Name:</label>
                        {{ form.last_name|add_class:"form-control" }}
                        {% if form.last_name.errors %}
                            <div class="text-danger">{{ form.last_name.errors.as_text }}</div>
                        {% endif %}
                    </div>

                    <div class="form-group">
                        <label for="id_email">Email:</label>
                        <input type="email" name="email" value="{{ user.email }}" maxlength="50" required=""
                               id="id_email" class="form-control">
                        {% if form.errors.email %}
                            <div class="text-danger">{{ form.errors.email }}</div>
                        {% endif %}
                    </div>

                    <div class="form-group">
                        <label for="id_age">Age:</label>
                        <input type="number" name="age" value="{{ user.age }}" min="0" id="id_age" class="form-control">
                        {% if form.errors.age %}
                            <div class="text-danger">{{ form.errors.age }}</div>
                        {% endif %}
                    </div>

                    <div class="form-group">
                        <label for="id_profile_picture">Profile picture:</label>
                        {% if user.profile_picture %}
                            <br>
                            <input type="checkbox" name="profile_picture-clear" id="profile_picture-clear_id">
                            <label for="profile_picture-clear_id">Clear</label>
                        {% endif %}
                        <br>
                        Change:
                        <input type="file" name="profile_picture" accept="image/*" id="id_profile_picture"
                               class="form-control-file">
                    </div>

                    <div class="form-group">
                        <label for="id_delivery_address">Delivery address:</label>
                        <textarea name="delivery_address" cols="32" rows="3" id="id_delivery_address"
                                  class="form-control">{{ user.delivery_address }}</textarea>
                        {% if form.errors.delivery_address %}
                            {{ form.errors.delivery_address }}
                        {% endif %}
                    </div>

                    <a href="{% url 'password-change' %}" class="btn btn-primary mt-2">Change password</a>
                    <button type="submit" class="btn btn-primary mt-2">Update Profile</button>

                </form>


            </div>
            <div class="col-md-6">
                <table class="table table-bordered table-striped">
                    <tbody>

                    <tr>
                        <td colspan="2" class="colhead colhead_fix bg-secondary text-white" style="height: 40px;">
                            Profile Overview
                        </td>
                    </tr>
                    <tr>
                        <td>Profile Picture</td>
                        <td>
                            {% if user.profile_picture %}
                                <img src="{{ user.profile_picture.url }}" alt="Profile Picture"
                                     class="img-fluid rounded-circle" style="max-height: 200px;">
                            {% else %}
                                <img src="{% static 'images/default_profile_picture.svg' %}" alt="Profile Picture"
                                     class="img-fluid rounded-circle" style="min-height: 200px;">
                            {% endif %}
                        </td>
                    </tr>
                    <tr>
                        <td>Username</td>
                        <td>{{ user.username }}</td>
                    </tr>
                    <tr>
                        <td>Full Name</td>
                        <td>{{ user.first_name }} {{ user.last_name }}</td>
                    </tr>
                    <tr>
                        <td>Email</td>
                        <td>{{ user.email }}</td>
                    </tr>
                    <tr>
                        <td>Registration Date</td>
                        <td>{{ user.date_joined }}</td>
                    </tr>
                    <tr>
                        <td>Age</td>
                        <td>{{ user.age }}</td>
                    </tr>
                    <tr>
                        <td>Delivery Address</td>
                        <td>
                            {{ user.delivery_address }}
                        </td>
                    </tr>
                    <tr>
                        <td>Reviews</td>
                        {% if total_comments %}
                            <td>{{ total_comments }}</td>
                        {% else %}
                            <td>No comments yet</td>
                        {% endif %}
                    </tr>
                    <tr>
                        <td>My Orders</td>
                        <td>
                            <a href="{% url 'my-orders' %}" class="btn btn-primary">View My Orders &#x2192;</a>
                        </td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}